name: advanced_nic_decoder
description: "A Flutter application to decode Sri Lankan NIC numbers."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management & navigation
  get: ^4.6.6
  get_storage: ^2.1.1

  # Local database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11

  # Utility libraries
  intl: ^0.20.2
  fl_chart: ^0.70.2  # For future graphing/stats if needed
  qr_flutter: ^4.1.0  # For QR code generation
  mobile_scanner: ^6.0.6  # For scanning QR codes

  # Google Fonts for styling
  google_fonts: ^6.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.6  # Needed for Hive code generation
  hive_generator: ^2.0.1 # Generates the adapter files for Hive

flutter:
  uses-material-design: true

  # Add assets if needed in future
  assets:
    - assets/images/
